title: Wangyuxuan Zhai Homepage
page-top-title: Wangyuxuan Zhai Homepage
top-section-bg-text: o(=•ェ•=)m
home-subtitle: Wangyuxuan Zhai
copyright-text: '&copy; Wangyuxuan Zhai 2025. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
