title: Wangyuxuan Zhai Homepage
page-top-title: Wangyuxuan Zhai Homepage
top-section-bg-text: 做长期主义的事，做理想主义的事。Do things that adhere to long-termism and do things that are driven by idealism.
home-subtitle: Wangyuxuan Zhai
copyright-text: '&copy; Wangyuxuan Zhai 2025. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
